services:
  postgres:
    image: postgres:16
    container_name: coffee_shop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_shop
    ports:
      - "5432:5432"
    volumes:
      - coffee_shop_pgdata:/var/lib/postgresql/data

volumes:
  coffee_shop_pgdata:
